name: Run python unit tests

on:
  pull_request:
    paths:
      - '**.py'
    branches:
      - main  # Change this to match your default branch
  push:
     paths:
      - '**.py'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_GOOGLE_SCOPES: "[\"https://www.googleapis.com/auth/gmail.readonly\", \"openid\"]"
          envkey_GOOGLE_CLIENT_ID: your-client-id-here
          envkey_COOKIE_SECRET: your-random-secret-here
          envkey_GOOGLE_API_KEY: your-api-key-here
          envkey_REDIRECT_URI: http://localhost:8000/login
          envkey_ENV: dev
          envkey_DB_PORT: 5432
          envkey_DB_HOST: your-db-host-here
          envkey_DB_NAME: your-db-name-here
          envkey_DB_USER: your-db-user-here
          envkey_DB_PASSWORD: your-db-password-here
          envkey_CLIENT_SECRETS_FILE: "credentials.json"
          directory: backend

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Set your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # Adjust if needed

      - name: Run Pytest
        run: | 
          # Load environment variables from .env file
          set -o allexport
          source backend/.env
          set +o allexport
          pytest --maxfail=5 --disable-warnings  # Modify flags as needed
